version: '3.7'
services:
sample-app:
    container_name: sample-container
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - '.:/usr/src/app'
      - '/usr/src/app/node_modules'
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=development