version: '3.7'
services:
web:
    image: aommiizz/ux-search-frontend:latest
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    networks:
      - webnet
networks:
  webnet: